### ISSUE TITLE
More detailed schematics?

### ISSUE THREAD

**Issue by robcazzaro** [trentfehl/chamber#10]
Thanks so much for publishing this. I would like to learn more about the H bridge implementation of this project, but I can find only a block diagram and the code. I could find no details on the type of H bridge used, nor of the circuit to drive the fans (is it just a GPIO input directly to the fan? if so, what fans did you use)?

Can you please share additional info on the components used? I did find the temp sensor info in the code (Amphenol TK95F232V NTC thermistor), but not much else

**Comment by trentfehl** [comment]
I added a link to the BOM in the README (under the block diagram). Yep, the fans are just driven by GPIOs - that's probably a place to improve here :)

**Comment by robcazzaro** [comment]
Thanks!
